# For deploy gitlab pages
pages:
  image: node:latest
  stage: deploy
  script:
    - cp src/common/config.js.template src/common/config.js
    - sed -i "s|CHANGEME_API_URL|$API_URL|" src/common/config.js
    - sed -i "s|CHANGEME_API_KEY|$API_KEY|" src/common/config.js
    - yarn
    - yarn build
    - mv public public-vue
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master

