# For deploy gitlab pages
pages:
  image: node:latest
  stage: deploy
  script:
    - yarn
    - yarn build
    - mv public public-vue
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
    - 6-split-search-vue-in-multiple-components

